sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t prebend/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true prebend/dockerreact npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-622811839783"
  bucket_path: "dockerreact"
  on:
    branch: master
  
  access_key_id: $AwsAccessKey
  secret_access_key: "$AwsSecretKey"
